### ISSUE TITLE
IAM

### ISSUE THREAD

**Issue by Oguzyildirim** [spati-java/spring-boot-java-highlevel-rest-client-elasticsearch#1]
Hello there, thank you this great tutorial but i want to ask you how can we add only IAM users access to database? because i have a data from external sources and i can't expose them public in my final year project.

**Comment by spati-java** [comment]
There are several ways to implement IAM , for example you can use, AWS IAM, or Google Cloud Platform IAM . To deal with RBAC in elasticsearch you can x-pack. Take a look at 

https://www.elastic.co/guide/en/kibana/current/development-security-rbac.html

This is not in the scope of this project as of now. We will see if we can implement this in the future.
